Friend Module GameState
    Friend Const ActionMenu = "ActionMenu"
    Friend Const Attack = "Attack"
    Friend Const Combat = "Combat"
    Friend Const Craft = "Craft"
    Friend Const Dead = "Dead"
    Friend Const Drop = "Drop"
    Friend Const Equip = "Equip"
    Friend Const Equipment = "Equipment"
    Friend Const EquipmentDetail = "EquipmentDetail"
    Friend Const Forage = "Forage"
    Friend Const Ground = "Ground"
    Friend Const Inventory = "Inventory"
    Friend Const InventoryDetail = "InventoryDetail"
    Friend Const Interact = "Interact"
    Friend Const Message = "Message"
    Friend Const Navigation = "Navigation"
    Friend Const Run = "Run"
    Friend Const Status = "Status"
    Friend Const Take = "Take"
    Friend Const Unequip = "Unequip"
End Module
