Friend Module GameState
    Friend Const ActionMenu = "ActionMenu"
    Friend Const Ground = "Ground"
    Friend Const GroundDetail = "GroundDetail"
    Friend Const GroundItem = "GroundItem"
    Friend Const InteractCharacter = "InteractCharacter"
    Friend Const Inventory = "Inventory"
    Friend Const Message = "Message"
    Friend Const MoveNorth = "MoveNorth"
    Friend Const MoveSouth = "MoveSouth"
    Friend Const MoveWest = "MoveWest"
    Friend Const MoveEast = "MoveEast"
    Friend Const Navigation = "Navigation"
    Friend Const Statistics = "Statistics"
    Friend Const Take = "Take"
    Friend Const TitsUp = "TitsUp"
End Module
