Friend Module StatisticTypes
    Friend Const AttackDice = "AttackDice"
    Friend Const DefendDice = "DefendDice"
    Friend Const Dignity = "Dignity"
    Friend Const DignityBuff = "DignityBuff"
    Friend Const Durability = "Durability"
    Friend Const Encumbrance = "Encumbrance"
    Friend Const Health = "Health"
    Friend Const MaximumAttack = "MaximumAttack"
    Friend Const MaximumDefend = "MaximumDefend"
    Friend Const MaximumDurability = "MaximumDurability"
    Friend Const MaximumEncumbrance = "MaximumEncumbrance"
    Friend Const MaximumHealth = "MaximumHealth"
    Friend Const SelectedItemId = "SelectedItemId"
    Friend Const TargetCharacterId = "TargetCharacterId"
End Module
